basic.forever(function () {
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(740, music.beat(BeatFraction.Half))
    basic.pause(50)
    music.playTone(698, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(622, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(554, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(554, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(415, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(554, music.beat(BeatFraction.Half))
    basic.pause(50)
    music.playTone(494, music.beat(BeatFraction.Half))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Half))
    basic.pause(50)
    music.playTone(370, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(415, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(100)
})
basic.forever(function () {
	
})
